Nizami/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Nizami.Models;

// Gets cart objects to be used to make the cart summary on the main page navbar
namespace Nizami.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Nizami/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Nizami.Models;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using Microsoft.Extensions.Options;
using System.Linq;
using Nizami.Models.ViewModels;
using System.ComponentModel;
using Microsoft.AspNetCore.Authorization;

namespace Nizami.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private IProductRepository repository;
        public int PageSize = 20; 
        public HomeController(IProductRepository repo)
        {
            repository = repo;
        }

        [AllowAnonymous]
        public ViewResult Index(string category, int sort=0, int page = 1)
            => View(new ProductsListViewModel
            {
                Products = repository.Products
                                .Where(p => category == null || p.Category == category)
                                .OrderBy(p => (sort == 1) ? p.Price : p.ProductID)
                                .Skip((page - 1) * PageSize)
                                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                         repository.Products.Count() :
                         repository.Products.Where(e =>
                         e.Category == category).Count()
                },
                CurrentCategory = category,
                SortPrice = sort
            });

        public ViewResult PostLogin(string category, int sort = 0, int page = 1)
                 => View(new ProductsListViewModel
                 {
                     Products = repository.Products
                                .Where(p => category == null || p.Category == category)
                                .OrderBy(p => (sort == 1) ? p.Price : p.ProductID)
                                .Skip((page - 1) * PageSize)
                                .Take(PageSize),
                     PagingInfo = new PagingInfo
                     {
                         CurrentPage = page,
                         ItemsPerPage = PageSize,
                         TotalItems = category == null ?
                         repository.Products.Count() :
                         repository.Products.Where(e =>
                         e.Category == category).Count()
                     },
                     CurrentCategory = category,
                     SortPrice = sort
                 });

        public IActionResult Privacy()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult FAQ()
        {
            return View();
        }


        [AllowAnonymous]
        public ActionResult AboutMe()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Nizami/Views/Home/AboutMe.cshtml
<!DOCTYPE html>
<html>
<head>
<style>
body {
  font-family: Arial;
  margin: 0;
  font-weight: bold;
}

html {
  box-sizing: border-box;
}

.header {
                padding: 30px;
                text-align: center;
                background: #343a40;
                color: white;
                font-size: 30px;
            }
            
*, *:before, *:after {
  box-sizing: inherit;
}

.column {
  float: left;
  width: 33.3%;
  margin-bottom: 16px;
  padding: 0 8px;
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  margin: 8px;
}

.about-section {
  padding: 50px;
  text-align: center;
  background-color: #68abde;
  color: white;
}

.container {
  padding: 0 16px;
          background-color: #68abde;
}
.row{
          background-color: #343a40;
}

.container::after, .row::after {
  content: "";
  clear: both;
  display: table;
}

.title {
  color: white;
}

.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
}

.button:hover {
  background-color: #555;
}

@@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: block;
            background-color: #343a40
  }
 
</style>
</head>
<body>

<div class="header">
            <h1>Nizami</h1>
        </div>

<div class="about-section">
  <h1>About Nizami</h1>
  <h2>Mission Statement:<h2>
  <h2>"To inspire healthier communities by connecting people to food"</h2>
  <p>Our mission has been to encourage healthier habits by providing organic 
     options for our customers. We at Nizami believe that a healthier diet
     is essential for living a better life. By prodiving organic options for
     our customers we at Nizami hope to encourage healthier living, because an organic 
     life is a better life!.</p>
  <h2>The Nizami Story</h2>
  <p>Nizami was founded in 1987 by Miyawaki Nizami in Jacksonville, Florida.
     Miyawaki immigrated to the United States from Japan in the 1950s searching for
     new opportunities after the war destroyed his family's grocery store. 
     Miyawaki settled in Florida and worked in local grocery store for several years.
     Miyawaki started out as a cashier and worked his way up to eventually becoming the
     manager of the store, with his bosses commenting that they had never seen a more diligent worker.
     Despite his success as a store manager, Miyawaki longed for something different. After spending 
     several years saving up money, together with his wife and two sons Miyawaki opened their
     own grocery store, Nizami. Nizami has been proud to serve the Jacksonville community for the 
     past 35 years, and we hope to keep serving you for many more!</p>
   <h2>Core Values</h2>
   <p>While working his first job as a cashier, Miyawaki's bosses instilled the belief of treating
      his customers like royalty. Miyawaki has carried this belief with him throughout his time in 
      the supermarket industry and is the core value that drives Nizami. Miyawaki believed that 
      building rapport with his customers would lead to long lasting customer relationships. Miyawaki
      encouraged his employees to treat his customers like they were family saying that "we're not a
      business, we're family, if we treat our customers like they're one of us, they'll keep coming
      back for more!" We at Nizami pride ourselves in catering to the needs of our customers and 
      providing a high quality customer service experience. </p>
</div>

    <h2 style="text-align:center; background-color: #343a40; color:white;">Our Team</h2>
    <div class="row">
  <div class="column">
    <div class="card">
      <img src= alt="Jane" style="width:100%">
      <div class="container">
        <h2>Jane De</h2>
        <p class="title">CEO & Founder</p>
        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
        <p>jane@example.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src= alt="Mike" style="width:100%">
      <div class="container">
        <h2>Mike Ross</h2>
        <p class="title">Art Director</p>
        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
        <p>mike@example.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>
  
  <div class="column">
    <div class="card">
      <img src= alt="John" style="width:100%">
      <div class="container">
        <h2>John Doe</h2>
        <p class="title">Designer</p>
        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
        <p>john@example.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>
</div>

</body>
</html>

Nizami/Views/Home/Index.cshtml
@model ProductsListViewModel
@{
    ViewData["Title"] = "Home Page";
}

@section Img{
	<a class="navbar-brand" id="navbar-logo" asp-area="" asp-controller="Home" asp-action="Index">
       <img src="/logo/svg/logo-no-background.svg" alt="" width="120" height="100" class="d-inline-block align-text-top">
    </a>
}

@section Navigation{
    <!--Header and buttons-->
	<li class="nav-item">
		<!--AccountMod4: asp-route-returnurl-->
		<a class="btn" asp-controller="Account" asp-action="UserSignUp" asp-route-returnurl="@ViewContext.HttpContext.Request.UserSignUp()">
			Sign Up
		</a>
	</li>

	<li class="nav-item">
		<!--AccountMod5: asp-route-returnurl-->
		<a class="btn" asp-controller="Account" asp-action="UserLogin" asp-route-returnurl="@ViewContext.HttpContext.Request.UserLogin()">
			Log In
		</a>
	</li>
}

@section AdminLogin{
	<ul class="navbar-nav ml-auto">
		<li class="nav-link">Are you an Administrator for this page?</li>
		<!--AccountMod1: asp-route-returnurl-->
		<li class="nav-item">
			<a class="btn" asp-controller="Account" asp-action="AdminLogin" asp-route-returnurl="@ViewContext.HttpContext.Request.AdminLogin()">
				Log in Here
			</a>
		</li>
	</ul>
}

@section Products{	
	@foreach (var p in Model.Products)
	{
		@Html.Partial("ProductSummary/Default", p)								
	}
}

@section Pagination{
	<!--HomeMod1/HomeMode3-->
	<nav>
		<div page-model="@Model.PagingInfo" page-action="Index" page-classes-enabled="true"
		 page-class="page-link"
		 page-class-selected="current-page" page-url-category="@Model.CurrentCategory" page-url-sort="@Model.SortPrice" id="pageNumber">
		</div>
	</nav>
}

@section SortPrice{
	@{

		if (Model.SortPrice == 1)
		{
			<!--HomeMod2/HomeMode3-->
			<a class="nav-link active" asp-action="Index" asp-controller="Home" asp-route-page="1" asp-route-sort="0">Unsort by Price</a>
		}
		else{
			<!--HomeMode3-->
			<a class="nav-link active" asp-action="Index" asp-controller="Home" asp-route-page="1" asp-route-sort="1">Sort by Price</a>
		}

	}
}

Nizami/Views/Home/PostLogin.cshtml
@model ProductsListViewModel
@{
	ViewData["Title"] = "Home Page";
	Layout = "_IndexLayout";
}

@section Img{
	<a class="navbar-brand" id="navbar-logo" asp-area="" asp-controller="Home" asp-action="PostLogin">
		<img src="/logo/svg/logo-no-background.svg" alt="" width="120" height="100" class="d-inline-block align-text-top">
	</a>
}

@section Logout{
	<ul class="navbar-nav ml-auto">
		<li class="nav-item">
			<a class="btn" asp-action="Logout" asp-controller="Account">Log Out</a>
		</li>
	</ul>
}

@section Cart{
	@await Component.InvokeAsync("CartSummary")
}

@section Products{
		@foreach (var p in Model.Products)
		{
			@Html.Partial("ProductSummary/PostLogin", p)
		}
}

@section Pagination{
	<!--HomeMod1/HomeMode3-->
	<nav>
		<div page-model="@Model.PagingInfo" page-action="PostLogin" page-classes-enabled="true"
		 page-class="page-link"
		 page-class-selected="current-page" page-url-category="@Model.CurrentCategory" page-url-sort="@Model.SortPrice" id="pageNumber">
		</div>
	</nav>
}

@section SortPrice{
	@{

		if (Model.SortPrice == 1)
		{
	<!--HomeMod2/HomeMode3-->
	<a class="nav-link active" asp-action="PostLogin" asp-controller="Home" asp-route-page="1" asp-route-sort="0">Unsort by Price</a>
		}
		else
		{
	<!--HomeMode3-->
	<a class="nav-link active" asp-action="PostLogin" asp-controller="Home" asp-route-page="1" asp-route-sort="1">Sort by Price</a>
		}
	}
}