Nizami/Components/NavigationMenuViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nizami.Models;


namespace Nizami.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IProductRepository repository;
        public NavigationMenuViewComponent(IProductRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repository.Products
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x));
        }
    }
}

Nizami/Views/Shared/ProductSummary.cshtml
@using Nizami.Infrastructure
@model Product

<!--This html code generates a list of cards with product info-->
<div class="col">
	<div class="card h-100" id="productCards">

		<img src="@Model.Image" class="card-img-top h-50" alt="">

		<div class="card-body">

			<h3>@Model.Name</h3>
			<p>@Model.Description</p>
			<p>@Model.Price.ToString("c")</p>

			<form id="@Model.ProductID" asp-action="AddToCart"
				  asp-controller="Cart" method="post">
				<input type="hidden" asp-for="ProductID" />
				<input type="hidden" name="returnUrl"
					   value="@ViewContext.HttpContext.Request.Path.ToString()" />
				<button type="submit" class="btn btn-info btn-sm float-right">
					Add To Cart
				</button>
			</form>

		</div>
	</div>
</div>

Nizami/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>

    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>

    <head>
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
        <title>@ViewBag.Title</title>
    </head>

    <body>
        <div class="container">
            <div class="card">
                <div class="card-header">
                    <h4>@ViewBag.Title</h4>
                @RenderSection("Logout", false)
                </div>
                <div class="card-body">
                    @if (TempData["message"] != null)
                     {
                        <div class="alert alert-success">@TempData["message"]</div>
                     }

                    @RenderBody()
                </div>
            </div>
        </div>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

Nizami/Views/Shared/_CartLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nizami</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" asp-href-include="lib/font-awesome/css/*.css" />
    <link rel="stylesheet" href="~/css/cart.css" asp-append-version="true" />
</head>

<body>
    @RenderBody()

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Nizami/Views/Shared/_FormLayout.cshtml
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>@ViewData["Title"] - Nizami</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/Nizami.styles.css" asp-append-version="true" />
        <link rel="stylesheet" asp-href-include="lib/font-awesome/css/*.css" />
    </head>

    <style>
        .gradient-custom {
            /* fallback for old browsers */
            background: #6a11cb;
            /* Chrome 10-25, Safari 5.1-6 */
            background: -webkit-linear-gradient(to right, rgb(60, 179, 113), rgb(94, 164, 71));
            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            background: linear-gradient(to right, rgb(60, 179, 113), rgb(94, 164, 71))
        }
    </style>

    <body>
        <section class="vh-100 gradient-custom">
            <div class="container py-5 h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                        <div class="card bg-dark text-white" style="border-radius: 1rem;">
                            <div class="card-body p-5 text-center">
                                @RenderSection("Form", true)
                            </div>
                        </div>
                    </div>
                    @RenderSection("Reset", false)
                </div>
            </div>
        </section>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/index.js" asp-append-version="true" defer></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

Nizami/Views/Shared/_IndexLayout.cshtml
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>@ViewData["Title"] - Nizami</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/Nizami.styles.css" asp-append-version="true" />
        <link rel="stylesheet" asp-href-include="lib/font-awesome/css/*.css" />
    </head>

    <body>
        <!--Navigation Bar-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">

                @RenderSection("Img", false)
                <!--When window size decreases, this button will be rendered to display a drop down menu with the nav-items inside of it-->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        @RenderSection("Navigation", false)
                        <li class="nav-item">
                            <a class="btn" asp-controller="Home" asp-action="AboutMe">
                                About Me Page
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="btn" asp-controller="Home" asp-action="FAQ">
                                FAQ Page
                            </a>
                        </li>
                        <li class="nav-item">@RenderSection("SortPrice",false)</li>
                        <li class="nav-item">@await Component.InvokeAsync("NavigationMenu")</li>
                        @RenderSection("Cart", false)
                    </ul>
                    @RenderSection("AdminLogin", false)
                    @RenderSection("Logout", false)
                </div>
            </div>
        </nav>

        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Welcome to Nizami</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Explore the best quality products Jacksonville has to offer</p>
                </div>
            </div>
        </header>

        <!--Main Body-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    @RenderSection("Products", false)
                </div>
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    @RenderSection("Pagination", false)
                </div>
            </div>
        </section>


        <footer class="text-white text-center text-lg-start bg-dark">
          
            <div class="container p-4">
                <div class="row mt-4">
          
                    <div class="col-lg-4 col-md-12 mb-4 mb-md-0">
                        <h5 class="text-uppercase mb-4">About company</h5>
                        <p>
                            Our mission has been to encourage healthier habits by providing organic
                            options for our customers. We at Nizami believe that a healthier diet
                            is essential for living a better life. By prodiving organic options for
                            our customers we at Nizami hope to encourage healthier living, because an organic
                            life is a better life!
                        </p>
                    </div>
                    
                    <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase mb-4 pb-1">Contact Information</h5>
                        <ul class="fa-ul" style="margin-left: 1.65em;">
                            <li class="mb-3">
                                <span class="fa-li"><i class="fas fa-home"></i></span><span class="ms-2">Santa Isabel, 00357, Puerto Rico</span>
                            </li>
                            <li class="mb-3">
                                <span class="fa-li"><i class="fas fa-envelope"></i></span><span class="ms-2">nizami@business.com</span>
                            </li>
                            <li class="mb-3">
                                <span class="fa-li"><i class="fas fa-phone"></i></span><span class="ms-2">+1 787 123 2456</span>
                            </li>
                        </ul>
                    </div>

                    <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase mb-4">Opening hours</h5>

                        <table class="table text-center text-white">
                            <tbody class="fw-normal">
                                <tr>
                                    <td>Mon - Thu:</td>
                                    <td>8am - 9pm</td>
                                </tr>
                                <tr>
                                    <td>Fri - Sat:</td>
                                    <td>8am - 1am</td>
                                </tr>
                                <tr>
                                    <td>Sunday:</td>
                                    <td>9am - 10pm</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>

            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                <p class="m-0 text-center text-white">Copyright &copy; Nizami 2022</p>
            </div>
        </footer>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        @await RenderSectionAsync("Scripts", required: false)

    </body>
</html>

Nizami/Views/Shared/_OrderLayout.cshtml
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>@ViewData["Title"] - Nizami</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/Nizami.styles.css" asp-append-version="true" />
        <link rel="stylesheet" asp-href-include="lib/font-awesome/css/*.css" />
    </head>

    <style>
        body{
            /* fallback for old browsers */
            background: #6a11cb;
            background: -webkit-linear-gradient(to right, rgb(193, 46, 192), rgb(119, 46, 192));
            background: linear-gradient(to right, rgb(193, 46, 192), rgb(119, 46, 192))
        }
    </style>

    <body>
            @RenderBody()
            <script src="~/lib/jquery/dist/jquery.min.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
            @await RenderSectionAsync("Scripts", required: false)

    </body>
</html>